# Generated by Django 5.0.3 on 2024-03-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prize',
            new_name='price',
        ),
    ]
